<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bolos Deliciosos</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>Bolos Deliciosos</h1>
        <nav>
            <ul>
                <li><a href="#">Início</a></li>
                <li><a href="#">Sobre Nós</a></li>
                <li><a href="#">Contatos</a></li>
            </ul>
        </nav>
    </header>
    
    <main>
        <section class="hero">
            <h2>Os melhores bolos da cidade!</h2>
            <p>Feitos com amor e ingredientes de qualidade.</p>
        </section>

        <section class="produtos">
            <h2>Nossos Bolos</h2>
            <div class="produto">
                <img src="bolo-chocolate.jpg" alt="Bolo de Chocolate">
                <h3>Bolo de Chocolate</h3>
                <p>R$ 50,00</p>
                <button>Comprar</button>
            </div>
            <div class="produto">
                <img src="bolo-vanilla.jpg" alt="Bolo de Baunilha">
                <h3>Bolo de Baunilha</h3>
                <p>R$ 45,00</p>
                <button>Comprar</button>
            </div>
            <div class="produto">
                <img src="bolo-frutas.jpg" alt="Bolo de Frutas">
                <h3>Bolo de Frutas</h3>
                <p>R$ 55,00</p>
                <button>Comprar</button>
            </div>
        </section>
    </main>

    <footer>
        <p>&copy; 2024 Bolos Deliciosos. Todos os direitos reservados.</p>
    </footer>
</body>
</html>
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
